---
title: "Informe Contexto Demográfico del Régimen"
subtitle: "Grupo 3"
author:
  - "Maria Carolina Navarro Monge C05513"
  - "Tábata Picado Carmona C05961"
  - "Jimena Marchena Mendoza B74425"
  - "Valentin Chavarría Ubeda B82098"

output:
  pdf_document:
    latex_engine: xelatex
    toc: true
 
header-includes:
  - \usepackage[spanish, provide=*]{babel}
  - \usepackage{titling}
  - \usepackage{fontspec}
  - \usepackage{wrapfig}
  - \setmainfont{Arial}
  - \usepackage{xcolor}
  - \definecolor{azul}{RGB}{49, 126, 153 }
  - \definecolor{gris}{RGB}{12, 76, 99}
  - \usepackage{sectsty}
  - \sectionfont{\color{azul}}
  - \subsectionfont{\color{gris}}
  - \usepackage{longtable}
  - \usepackage[table]{xcolor}
  - \usepackage{geometry}
  - \usepackage{array} 
  - \usepackage{makecell} 
  - \usepackage{multirow}
  - \geometry{a4paper, margin=1in}
  - \definecolor{turquoise}{RGB}{0, 139, 139}
  - \usepackage{graphicx} 
  - \usepackage{caption}
  - \captionsetup{singlelinecheck=off}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
\newpage

# Marco Legal

\begingroup
\small
\begin{longtable}{|m{4cm}|m{10cm}|m{1.3cm}|}
\caption{Reglamento del Régimen de Invalidez, Vejez y Muerte de la Caja Costarricense del Seguro Social} \\
\hline
\rowcolor{turquoise}
\multicolumn{1}{|c|}{\textbf{Rubro}} & \multicolumn{1}{c|}{\textbf{Resumen}} & \multicolumn{1}{c|}{\textbf{Artículo}} \\
\hline
\endhead 
Alternativas de pensión por vejez & \begin{itemize}
    \item \textbf{Pensión por vejez ordinaria:} El asegurado que alcance los 65 años de edad, siempre que haya contribuido a este Seguro con al menos 300 cuotas.
    \item \textbf{Pensión por vejez proporcional:} Aquellos asegurados que habiendo alcanzado 65 años de edad, no hayan aportado 300 cuotas, pero acumularon al menos 180, tienen derecho a una pensión proporcional.
    \item \textbf{Pensión por vejez anticipada para mujeres:} Según edad y cuotas a partir de los 63 años.
    \item \textbf{Pensión por vejez anticipada según el artículo 26 de la Ley de Protección al Trabajador:} El asegurado podrá anticipar su retiro, utilizando los recursos acumulados en el Régimen Voluntario de Pensiones Complementarias, una vez aprobado por la Junta Directiva.
    \item \textbf{Pensión por vejez para personas con Síndrome de Down:} Dada su condición genética que conlleva a un envejecimiento prematuro, se establece como edad mínima de retiro por vejez, 40 años con 180 cotizaciones.
\end{itemize} & Art. 5 \\
\hline
Pensión por invalidez & Tiene derecho a la pensión por invalidez, el asegurado que sea declarado inválido por la Comisión Calificadora y siempre que haya aportado al menos 180 cotizaciones mensuales a la fecha de la declaratoria de invalidez o al menos doce cuotas durante los últimos 24 meses antes de la declaratoria si ocurre antes de los 48 años de edad o un mínimo de 24 cuotas durante los últimos 48 meses, si ocurre a los 48 ó más años de edad. En ambos casos se requiere, que cumpla el número de cotizaciones de acuerdo con la edad. & Art. 6 \\
\hline
Declaratoria de invalidez & Se crea la Comisión Calificadora del Estado de Invalidez encargada de valorar al asegurado que solicite una pensión por invalidez y de declarar si se encuentra o no inválido. & Art. 7 \\
\hline
Requisitos para pensionarse por invalidez & Se considerará inválido el asegurado que, por alteración o debilitamiento de su estado físico o mental, perdiera dos terceras partes o más de su capacidad de desempeño. También las personas que sean declaradas en estado de incurables o con pronóstico fatal. & Art. 8 \\
\hline
Requisitos para acogerse a la pensión en calidad de pareja supérstite & Tendrá este derecho:
 \begin{enumerate}
     \item El cónyuge sobreviviente del asegurado si al momento del fallecimiento, se encontraba conviviendo con el asegurado en el mismo hogar, o que por motivos de conveniencia o de salud de alguno de los cónyuges, vivía en una residencia distinta. En casos de separación, se debe demostrar que el causante le brindaba efectivamente una ayuda económica.
     \item La compañera o el compañero del asegurado fallecido que al momento del deceso haya convivido al menos tres años con él en el mismo hogar y haya dependido económicamente del causante. 
     \item La persona que haya mantenido una relación y que el único ingreso que percibía provenía del asegurado.
     \item La persona divorciada del asegurado que, al momento del fallecimiento, recibía de parte de éste pensión alimentaria.
 \end{enumerate}
No tendrá derecho a pensión el cónyuge o compañero sobreviviente cuando haya sido declarado autor o cómplice de la muerte. & Art. 9 \\
\hline
Reconocimiento de más de un derecho en calidad de pareja supérstite & Se podrá reconocer el derecho a más de una persona. La proporción de pensión para cada beneficiario será el porcentaje que le hubiese correspondido a uno solo dividido por el número de beneficiarios. & Art. 10 \\
\hline
Requisitos para acogerse a la pensión por viudez & Queda sujeto a los requisitos generales previstos en el artículo 18º de este Reglamento. & Art. 11 \\
\hline
\multirow{2}{=}{Requisitos para acogerse a pensión por orfandad} & Tienen derecho a pensión por orfandad los hijos que al momento del fallecimiento dependían económicamente del causante:
\begin{enumerate}
\renewcommand{\theenumi}{\alph{enumi}}
    \item Los solteros menores de 18 años de edad.
    \item Los menores de 25 años de edad, solteros,  y sean estudiantes que cumplan ordinariamente con sus estudios.
    \item Los inválidos.
    \item En ausencia del cónyuge del asegurado(a) o pensionado(a) fallecido(a), los hijos mayores de 55 años, solteros, que vivían con el fallecido, siempre que no gocen de pensión alimentaria, no sean asalariados y no tengan otros medios de subsistencia, en razón de limitaciones físicas, mentales o sociales. 
    \item Los hijos no reconocidos oficialmente por sentencia judicial si se determina que hubo posesión notoria de estado. Esto también se aplica a los hijos extramatrimoniales nacidos después del fallecimiento de uno de los padres. Solo  si existe la posibilidad de que el solicitante sea el hijo biológico.
\end{enumerate} & Art. 12 \\
\cline{2-3}
& Queda sujeto a que se cumplan los requisitos generales que se especifican en el artículo 18º de este Reglamento. & Art. 13 \\
\hline
\multirow{4}{=}[-1.5cm]{Condiciones y requisitos para pensión a otros sobrevivientes} & En ausencia de beneficiarios por viudez u orfandad, los padres tienen derecho a pensión si dependían económicamente del fallecido debido a limitaciones físicas, mentales o sociales. & Art. 14 \\
\cline{2-3}
 & En ausencia de padres con derecho, las personas que hubieren cuidado del asegurado fallecido tienen derecho a pensión por ascendencia si cumplen con las condiciones del artículo 14, según la calificación y comprobación de la Caja. & Art. 15 \\
\cline{2-3}
 & En ausencia de viuda, compañera, hijos ni padres, los hermanos dependientes económicamente del fallecido tienen derecho a pensión, según lo previsto en el artículo 12. Si el hermano es inválido, el derecho a pensión se supedita a que no reciba otra pensión de invalidez o del Régimen no Contributivo. & Art. 16 \\
\cline{2-3}
 & El derecho a pensión de padres y hermanos está sujeto a los requisitos y condiciones de los artículos 18 y 27 del Reglamento. & Art. 17 \\
\hline
Requisitos generales para otorgar pensiones a sobrevivientes & Los sobrevivientes que cumplen los requisitos y condiciones establecidos en los artículos 9 al 15 de este Reglamento, tienen derecho a pensión si el fallecido era pensionado por vejez o invalidez, aportó 180 cotizaciones mensuales o cotizó un mínimo de 12 cuotas durante los últimos 24 meses anteriores a la muerte.
 & Art. 18 \\
\hline
De la vigencia de los derechos & Los derechos rigen conforme a las siguientes reglas::
\begin{enumerate}
    \item \textbf{Invalidez:} Desde la fecha de declaración de invalidez por la Comisión Calificadora, desde la fecha de resolución judicial en caso de reclamos judiciales y el asegurado que sea declarado inválido por la Comisión Calificadora,desde el fin de los subsidios del Seguro de Enfermedad y Maternidad.
    \item \textbf{Vejez:} Desde la fecha de solicitud de pensión, cumpliendo los requisitos de cotización y edad y si está trabajando, desde el día siguiente a la terminación de la relación laboral.
    \item \textbf{Sobrevivientes:} Desde la fecha de fallecimiento. Para hijos póstumos, desde el nacimiento.

\end{enumerate} & Art. 19 \\
\hline
Fórmula de cálculo del salario promedio, periodicidad del pago de la pensión y aguinaldo. & El cálculo de la pensión por vejez o invalidez se basa en el promedio de los mejores 300 salarios mensuales ajustados por inflación, tomando como base de actualización el índice de precios al consumidor calculado mensualmente por el Instituto Nacional de Estadística y Censos de Costa Rica. Si no se han aportado 300 cuotas, se consideran todos los salarios reportados. Las pensiones se pagan mensualmente, con un aguinaldo adicional en diciembre.El primer pago comprenderá el período o fracción del mes desde la fecha de vigencia de la pensión. El aguinaldo se pagará en la primera semana de diciembre. & Art. 23 \\
\hline
Monto de las pensiones por vejez, invalidez o muerte & El monto comprende una cuantía básica como porcentaje del salario o ingreso promedio de referencia. Esta cuantía básica se otorga por los primeros 25 años cotizados (300 cuotas) o los que se tuvieren en caso de invalidez o muerte. Tanto para vejez como invalidez, se incluye una cuantía adicional del 0.0833\% sobre el salario promedio por cada mes cotizado en exceso de los primeros 300 meses. Para la pensión por vejez proporcional se calcula multiplicando la pensión completa por el número de cuotas aportadas y dividiendo por 300. En caso de invalidez, trabajadores con al menos 60 cuotas y sin cumplir los requisitos del artículo 6 tienen derecho a una pensión proporcional calculada como la proporción entre cuotas aportadas y requeridas, multiplicada por la pensión completa. La pensión complementaria de vejez para la persona inválida que trabaje es del 3\% del salario promedio por cada año cotizado.& Art. 24 \\
\hline
Pensión adicional por postergación del retiro & El asegurado que cumpla con los requisitos para pensión por vejez tiene derecho a una pensión adicional por postergar el retiro, del 0.1333$\%$ por mes sobre el salario promedio, sin exceder el 125$\%$ del salario promedio. & Art. 25 \\
\hline
Monto de la pensión por viudez, orfandad y a otros sobrevivientes & El monto de la pensión para viudez, orfandad y otros sobrevivientes es proporcional a la pensión de invalidez o vejez del fallecido. Para no pensionados, se calcula según la pensión por vejez que hubiera correspondido.
Proporciones para pensión:
\begin{itemize}
    \item Viudez:
    \begin{itemize}
        \item 70$\%$ si el viudo/a es mayor de 60 años o inválido.
        \item 60$\%$ si es mayor de 50 y menor de 60 años.
        \item 50$\%$ si es menor de 50 años.
    \end{itemize}
    \item Orfandad:
    \begin{itemize}
        \item 30$\%$ por cada huérfano.
        \item 60$\%$ para huérfanos de ambos padres.
    \end{itemize}
\end{itemize}

Si la suma de las pensiones de viudez y orfandad excede el 100\%, todas serán proporcionalmente reducidas para que la suma sea igual al 100\%. Si un beneficiario deja de recibir pensión, las pensiones de los demás se aumentarán proporcionalmente, sin exceder los porcentajes fijados.

Si la suma de las pensiones de viudez y orfandad es menor al 100\%, el remanente puede ser distribuido entre los padres del fallecido, hasta un 20\% por ascendiente. En ausencia de padres con derecho, el remanente puede distribuirse entre los hermanos, hasta un 20\% por hermano.& Art. 27 \\
\hline
\end{longtable}
\endgroup
\captionsetup{font=footnotesize} 
\begin{center}
\captionsetup{type=table} 
\caption*{\footnotesize Fuente: Sistema Costarricense de Información Jurídica.}
\end{center}