---
output:
  rmdformats::robobook:
        code_folding: show
  html_document:
    toc: TRUE
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(openxlsx)
library(readxl)
library(ggplot2)
library(tidyr)
library(zoo)
library(dplyr)
```
# Producto Interno Bruto

```{r}
PIB <- read_excel("PIB Trimestral.xlsx")
```

```{r}
PIB$Trimestre <- as.yearqtr(PIB$Trimestre)
```

```{r}
ggplot(PIB, aes(x = Trimestre, y = `Producto Interno Bruto a precios de mercado`)) +
  geom_line(color = "cadetblue3") +
  geom_point(color = "#2F4F4F") +
  labs(x = "Trimestre", y = "Producto Interno Bruto", title = "Evolucion del Producto Interno Bruto por trimestre en Costa Rica, 2022-2023") +
  theme_minimal()
```

```{r}
ggplot(PIB, aes(x = Trimestre, y = `Tasa de Variación Interanual`)) +
  geom_bar(stat = "identity", fill = "#2F4F4F", alpha = 0.7) + 
  labs(x = "Trimestre", y = "Tasa de Variación Interanual (%)", title = "Tasa de Variación Interanual del Producto Interno Bruto por trimestre en Costa Rica, 2022-2023") +
  theme_minimal()
```


# Variación de salarios 

```{r}
salarios_nominales <- read_excel("Variación de salarios nominales.xlsx")
salarios_reales <- read_excel("Variación de salarios reales.xlsx")
```

```{r}
salarios_nominales$Fecha <- as.yearmon(salarios_nominales$Fecha, format = "%B/%Y")
salarios_reales$Fecha <- as.yearmon(salarios_reales$Fecha, format = "%B/%Y")
```

```{r}
salarios_nominales_inter <- salarios_nominales[, c("Fecha", "Variación interanual (%)")]
salarios_reales_inter <- salarios_reales[, c("Fecha", "Variación interanual (%)")]
```

```{r}
variaciones_salarios <- merge(salarios_nominales_inter, salarios_reales_inter, by = "Fecha", suffixes = c(" nominal", " real"))
```

```{r}
variaciones_largas <- pivot_longer(variaciones_salarios, cols = c(`Variación interanual (%) nominal`, `Variación interanual (%) real`), names_to = "Tipo", values_to = "Variación")
```

```{r}
ggplot(variaciones_largas, aes(x = Fecha, y = Variación, fill = Tipo)) +
  geom_bar(stat = "identity", alpha = 0.7, position = position_dodge(width = 0)) +
  scale_fill_manual(values = c(`Variación interanual (%) nominal` = "#2F4F4F", `Variación interanual (%) real` = "cadetblue3"),
                    name = "Tipo de Variación",  # Define el nombre en la leyenda
                    labels = c("Variación Nominal", "Variación Real")) +  # Define las etiquetas
  labs(title = "Variaciones Interanuales del Índice de Salario Mínimo Nominal vs Real en Costa Rica,\n 2022-2023",
       x = "Fecha",
       y = "Variación (%)") +
  theme_minimal()
```

