---
title: "Pensiones/personal"
output: html_document
date: "2024-04-01"
---



```{r}
TipoCambio1 <- read.csv2("C:/Users/Jimena/Desktop/Pensiones/InformeEconomico/TipoCambio1.csv")
TipoCambio1 <- TipoCambio1[, -c(4:10)]
TipoCambio1$Fecha <- as.Date(TipoCambio1$Fecha, format = "%d/%m/%Y")
```

```{r}
library(ggplot2)
ggplot(TipoCambio1, aes(x = Fecha)) +
  geom_line(aes(y = TIPO.CAMBIO.COMPRA, color = "Compra")) +
  geom_line(aes(y = TIPO.DE.CAMBIO.VENTA, color = "Venta")) +
  scale_color_manual(values = c("Compra" = "#5F9EA0", "Venta" = "#7AC5CD")) +
  labs(x = "Fecha", 
       y = "Tipo de Cambio (colones)",
       title = "Tipo de cambio del dólar de los Estados Unidos de América", 
       subtitle = "Ene 2022 a Dic 2023",
       color = "Tipo de Cambio",
       caption = expression(bold("Fuente: ") * "Elaboración propia a partir de datos del BCCR."))+
  scale_y_continuous(limits = c(500, 700),  # Establece los límites del eje y
                     breaks = seq(500, 700, by = 20))+
   scale_x_date(date_labels = "%b-%Y", date_breaks = "2 month")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "bottom",
        plot.caption.position = "plot",
        plot.caption = element_text(hjust = 0),
        plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5))
```

```{r}
Inflacion <- read.csv2("C:/Users/Jimena/Desktop/Pensiones/InformeEconomico/Inflacion.csv")
Inflacion$Fecha <- as.Date(Inflacion$Fecha, format = "%d/%m/%Y")
```

```{r}
ggplot(Inflacion, aes(x = Fecha)) +
  geom_line(aes(y = `Variacion.mensual....`, color = "Variación Mensual"),size = 1.15) +
  geom_line(aes(y = `Variacion.interanual....`, color = "Variación Interanual"),size = 1.15) +
  geom_line(aes(y = `Variacion.acumulada.....n3`, color = "Variación Acumulada"),size = 1.15) +
  scale_color_manual(values = c("Variación Mensual" = "#5F9EA0", "Variación Interanual" = "#BCEE68", "Variación Acumulada" = "#00CDCD")) +
  labs(title = "Inflación",
       subtitle = "Ene 2022 a Dic 2023",
       x = "Fecha",
       y = "Variación",
       color = "Tipo de Variación",
       caption = expression(bold("Fuente: ") * "Elaboración propia a partir de datos del BCCR.")) +
  theme_minimal()+
  scale_y_continuous(labels = scales::percent_format(scale = 1), breaks = seq(-4, 13, by = 1))+
  geom_hline(yintercept = 2, linetype = "dashed", color = "black")+
  geom_hline(yintercept = 4, linetype = "dashed", color = "black")+
  scale_x_date(date_labels = "%b-%Y", date_breaks = "2 month")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "bottom",
        plot.caption.position = "plot",
        plot.caption = element_text(hjust = 0),
        plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5))
```



