---
title: "Variación de la población y migración"
output: html_document
encoding: UTF-8
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=FALSE,message=FALSE, echo=FALSE}
library(readxl)
library(tidyr)
library(dplyr)
library(ggplot2)
```

```{r, warning=FALSE, message=FALSE, echo=FALSE}
# Se añaden los datos de la población costarricense por edades quinquenales para
# hombres y mujeres
columna_edades <- read_excel("Poblacion.xlsx", range = "B33:B55")

#Datos hombres
columnas_hombres <- read_excel("Poblacion.xlsx", range = "N33:Q55")
Hombres_pob <- cbind(columna_edades, columnas_hombres)
Hombres_pob <- Hombres_pob[-1,]
colnames(Hombres_pob) <- c("Edades", "2022", "2023", "2024", "2025")
Hombres_pob_long <- Hombres_pob  %>% gather(Ano, Poblacion,"2022":"2025")
Hombres_pob_long$Sexo <-rep("Hombre", length(Hombres_pob_long))

#Datos mujeres 
columnas_mujeres <- read_excel("Poblacion.xlsx", range = "N57:Q79")
Mujeres_pob <- cbind(columna_edades, columnas_mujeres)
Mujeres_pob <- Mujeres_pob[-1,]
colnames(Mujeres_pob) <- c("Edades", "2022", "2023", "2024", "2025")
Mujeres_pob_long <- Mujeres_pob  %>% gather(Ano, Poblacion,"2022":"2025")
Mujeres_pob_long$Sexo <-rep("Mujer", length(Mujeres_pob_long) )

#datos con porcentajes por tres grupos de edad sin importar sexo
Pob_3rangos <- data.frame("Edades" = c("0-14", "15-64", "65 y mas"), 
                              `2022` = c(NA), `2023`= c(NA), `2024`= c(NA), 
                              `2025`= c(NA),  check.names = FALSE)
for(i in 2:5){
  pob_rango1 <- sum(Hombres_pob[1:3,i] + Mujeres_pob[1:3,i]) 
  pob_rango2 <- sum(Hombres_pob[4:13,i] + Mujeres_pob[4:13,i])
  pob_rango3 <- sum(Hombres_pob[14:21,i] + Mujeres_pob[14:21,i])
  pob_total <- pob_rango1 + pob_rango2 + pob_rango3

  Pob_3rangos[1,i] <-(pob_rango1/pob_total)*100
  Pob_3rangos[2,i] <-(pob_rango2/pob_total)*100
  Pob_3rangos[3,i] <-(pob_rango3/pob_total)*100
}

Pob_3rangos_long <- Pob_3rangos  %>% gather(Ano, Porcentaje,"2022":"2025")
```

# Variación de la población

A continuación, se presenta un análisis de la variación de la población durante 
el periodo 2022-2023, así como, de la proyección de la población para el 2024 y 2025. 
Para tal objetivo, se toma coma base datos la poblacion por años calendario, 
según sexo y grupos quinquenales de edades proporcionado por el Instituto Nacional 
de Estadística y Censos (INEC).

```{r,warning=FALSE, message=FALSE, echo=FALSE }
#Gráfico de barras

ggplot(Pob_3rangos_long, aes(x = Porcentaje, y = factor(Ano), fill = Edades)) +
   geom_bar(stat = "identity", alpha = 0.7, position = "stack", width = 0.4) +
  geom_text(aes(label = paste0(round(Porcentaje, 2), "%")), position = position_stack(vjust = 0.5), size = 3) +
  scale_fill_manual(values = c(`0-14` = "#2F4F4F", `15-64` = "cadetblue3",`65 y mas`= "#BCEE68"))+
  labs(title = "Estructura porcentual de la población según edad, en Costa Rica",
       subtitle = "2022-2025",
       x = "Años", 
       y = "Porcentaje (%)",fill = "Edad" ) +
    theme_minimal()+
  scale_y_discrete(limits = rev(levels(factor(Pob_3rangos_long$Ano)))) +  # Reordenar años en eje y
  theme(legend.position = "bottom",
        plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5),
        plot.caption = element_text(hjust = 0, color = "black", size = 8),
        legend.title = element_blank()) +
  labs(caption = expression(bold("Fuente: ") * "Elaborado a partir de datos del INEC."))
```
```{r, warning=FALSE, message=FALSE, echo=FALSE}
# Datos de ejemplo
datos_piramide <-rbind(Hombres_pob_long, Mujeres_pob_long)

# Convertir datos a formato largo y ajustar el valor de la población para los hombres
datos_piramide <- datos_piramide  %>%
  mutate(Poblacion = ifelse(Sexo == "Hombre", -Poblacion, Poblacion)) %>%
  mutate(Edades = factor(Edades, levels = unique(Edades)))

# Crear gráfico de barras con barras reflejadas
ggplot(datos_piramide, aes(x = Poblacion, y = Edades, fill = Sexo)) +
  geom_bar(stat = "identity", position = "identity") +
  scale_fill_manual(values = c("Hombre" = "#2F4F4F", "Mujer" = "cadetblue3")) +
  labs(title = "Pirámide Poblacional de Costa Rica",
       subtitle = "2022-2025",
       x = "Población", 
       y = "Edad", fill = "Sexo" ) +
  theme_minimal()+
  scale_x_continuous(labels = function(x) abs(x))+
   theme(legend.position = "bottom",
        plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5),
        plot.caption = element_text(hjust = 0, color = "black", size = 8),
        legend.title = element_blank()) +
  labs(caption = expression(bold("Fuente: ") * "Elaborado a partir de datos del INEC."))
```
