---
title: "Si usar"
author: "VChU"
date: "2024-06-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```


```{r}
nuevas_cotizaciones215 <- data.frame(
  edad = 116:215,
  Cotizaciones = rep(12, length(116:215))  # Repetir el valor 10
)
promedios_cotizaciones_edad_215 <- rbind(promedios_cotizaciones_edad, nuevas_cotizaciones215)

nuevas_variaciones215 <- data.frame(
  edad = 115:215,
  variacion = rep(0, length(115:215))  # Repetir el valor 10
)

variacion_proyectada_215 <- rbind(variacion_proyectada, nuevas_variaciones215)

Activos2023 <- activos %>% 
  dplyr::select(
    ID,
    Edad,
    `ene/2023`,
    `feb/2023`,
    `mar/2023`,
    `abr/2023`,
    `may/2023`,
    `jun/2023`,
    `jul/2023`,
    `ago/2023`,
    `sep/2023`,
    `oct/2023`,
    `nov/2023`,
    `dic/2023`
  ) %>% 
  dplyr::mutate(
    Salario =
      `ene/2023` +
      `feb/2023` +
      `mar/2023` +
      # `abr/2023` +
      `may/2023` +
      `jun/2023` +
      `jul/2023` +
      `ago/2023` +
      `sep/2023` +
      `oct/2023` +
      `nov/2023` +
      `dic/2023`,
    `ene_2023`=`ene/2023`>0,
    `feb_2023`=`feb/2023`>0,
    `mar_2023`=`mar/2023`>0,
    `abr_2023`=`abr/2023`>0,
    `may_2023`=`may/2023`>0,
    `jun_2023`=`jun/2023`>0,
    `jul_2023`=`jul/2023`>0,
    `ago_2023`=`ago/2023`>0,
    `sep_2023`=`sep/2023`>0,
    `oct_2023`=`oct/2023`>0,
    `nov_2023`=`nov/2023`>0,
    `dic_2023`=`dic/2023`>0,
    Cotizaciones =
      `ene_2023` +
      `feb_2023` +
      `mar_2023` +
      # `abr_2023` +
      `may_2023` +
      `jun_2023` +
      `jul_2023` +
      `ago_2023` +
      `sep_2023` +
      `oct_2023` +
      `nov_2023` +
      `dic_2023`,
    Mensual =
      Salario/Cotizaciones
  ) %>% 
  dplyr::select(
    ID,
    Edad,
    Mensual
  ) %>% 
  mutate(
    as.data.frame(
      # matrix(rep(Mensual,100),ncol = 100,byrow = F)*
      (1+inflacion)*matrix(
        (1+variacion_proyectada_215$variacion[outer(
          Edad - 18,
          1:100,
          "+"
        )]
        ),
        ncol = 100
      )*matrix(
        (promedios_cotizaciones_edad_215$Cotizaciones[outer(
          Edad - 18,
          1:100,
          "+"
        )]
        ),
        ncol = 100
      )
    )
  )


for (k in 1:length(Activos2023$ID)) {
  Activos2023[k,4:103] <- cumprod(Activos2023[k,4:103])*Activos2023$Mensual[k]
}

```

```{r}
d <- 0.04
cotizaciones_FUN <- function(dfActivos) {
  Cotizaciones_Activos <- dfActivos %>% 
    dplyr::select(
      ID,
      cont
    ) %>% 
    dplyr::mutate(
      Fila = match(
        ID,
        Activos2023$ID
      )
    ) %>% 
    cbind(
      matrix(numeric(100*length(dfActivos$ID)),ncol = 100)
    )
  
  for (i in 1:length(Cotizaciones_Activos$ID)) {
    Cotizaciones_Activos[i,3+1:Cotizaciones_Activos$cont[i]] <- Activos2023[Cotizaciones_Activos$Fila[i],3 + 1:Cotizaciones_Activos$cont[i]]
  }
  Cotizacion_Anuales <- colSums(Cotizaciones_Activos[4:103])*.15
  
  # View(data_frame(Cotizacion_Anuales))
  # 
  # sum(Cotizacion_Anuales*(1+d)^(1:100))
  retun <- list(
    "ANUAL" = Cotizacion_Anuales,
    PVC = sum(Cotizacion_Anuales*(1+d)^(1:100))
  ) 
  return(retun)
}
Balances_Activos <- lapply(lista_pensionados_activos, cotizaciones_FUN)
```


```{r}
Cotizaciones_Activos <- dfActivos %>% 
  dplyr::select(
    ID,
    cont
  ) %>% 
  dplyr::mutate(
    Fila = match(
      ID,
      Activos2023$ID
    )
  ) %>% 
  cbind(
    matrix(numeric(100*length(dfActivos$ID)),ncol = 100)
  )

for (i in 1:length(Cotizaciones_Activos$ID)) {
  Cotizaciones_Activos[i,3+1:Cotizaciones_Activos$cont[i]] <- Activos2023[Cotizaciones_Activos$Fila[i],3 + 1:Cotizaciones_Activos$cont[i]]
}
Cotizacion_Anuales <- colSums(Cotizaciones_Activos[4:103])*.15

plot(Cotizacion_Anuales)

 sum(Cotizacion_Anuales*(1+d)^(1:100))
```

```{r}
# Historico_Completo <- cbind(
#   activos %>% 
#     dplyr::select(
#     ID,
#     Edad
#   ),
#   activos[,4:363],
#   mensual_proyectado[,4:103]
# )

mensual_proyectado <- matrix(0,nrow = length(activos$ID),ncol = 1200)
for (k in 1:length(activos$ID)) {
  Edad1 <- activos$Edad[k]
  v1 <- 1 
  d1 <- 1
  for (a in 0:99) {
    v1 <- v1*1.04
    d1 <- d1*(1+variacion_proyectada_215$variacion[Edad1-18])
    densidad <- promedios_cotizaciones_edad_215$Cotizaciones[Edad1-18]
    mensual1 <- Activos2023$Mensual[k]*v1*d1
    mensual_proyectado[k,(a*12+(1:12))] <-  c(rep(mensual1,densidad),rep(0,12-densidad))
  }
}
mensual_completo <- cbind(activos[,4:363],mensual_proyectado)
pensiones_proyectados <- 0*mensual_completo
for (k in 1:length(activos$ID)) {
  pensiones_proyectados[k,] <- mensual_completo[k,]*(1+d)^-rep((-30):99, each = 12)
}
```


```{r}
dfActivos <- lista_pensionados_activos[[5]]

salarios_acumulados <- pensiones_proyectados*0
for (k in 1:length(dfActivos$ID)) {
  Edad1 <- dfActivos$Edad[k]
  salarios_acumulados[k,1:(30+Edad1)] <- pensiones_proyectados[k,1:(30+Edad1)]*(1+d)^Edad1
}

dim(mensual_proyectado)
```




